/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RusqliteColumn {
  name(): string
  declType(): string | null
}

export declare class RusqliteColumnMetadata {
  name(): string
  databaseName(): string | null
  tableName(): string | null
  originName(): string | null
}

export declare class RusqliteConnection {
  static open(path: string, options?: RusqliteConnectionOptions | undefined | null): RusqliteConnection
  static openInMemory(options?: RusqliteConnectionOptions | undefined | null): RusqliteConnection
}

export declare class RusqliteRow {
  get(index: string | number): string | number | Uint8Array | null
}

/**
 * This type extends JavaScript's `Iterator`, and so has the iterator helper
 * methods. It may extend the upcoming TypeScript `Iterator` class in the future.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iterator_helper_methods
 * @see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-6.html#iterator-helper-methods
 */
export declare class RusqliteRows extends Iterator<object, void, void> {

  next(value?: void): IteratorResult<object, void>
}

export interface RusqliteConnectionOptions {
  flags: number
  vfs?: string
}
