/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RusqliteColumn {
  name(): string
  declType(): string | null
}

export declare class RusqliteColumnMetadata {
  name(): string
  databaseName(): string | null
  tableName(): string | null
  originName(): string | null
}

export declare class RusqliteConnection {
  static open(path: string, options?: RusqliteConnectionOptions | undefined | null): RusqliteConnection
  static openInMemory(options?: RusqliteConnectionOptions | undefined | null): RusqliteConnection
}

export declare class RusqliteRow {
  get(index: string | number): string | number | Uint8Array | null
}

/**
 * This type extends JavaScript's `Iterator`, and so has the iterator helper
 * methods. It may extend the upcoming TypeScript `Iterator` class in the future.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iterator_helper_methods
 * @see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-6.html#iterator-helper-methods
 */
export declare class RusqliteRows extends Iterator<object, void, void> {

  next(value?: void): IteratorResult<object, void>
}

export declare class RusqliteStatement {
  columnNames(): Array<string>
  columnCount(): number
  columnName(col: number): string
  columnIndex(name: string): number
  columns(): Array<RusqliteColumn>
  columnsWithMetadata(): Array<RusqliteColumnMetadata>
  columnMetadata(col: number): RusqliteDetailedColumnMetadata | null
  execute(params?: unknown[] | undefined | null): number
  insert(params?: unknown[] | undefined | null): number
  query(params?: unknown[] | undefined | null): RusqliteRows
  exists(params?: unknown[] | undefined | null): boolean
  parameterIndex(name: string): number | null
  parameterName(index: number): string | null
  parameterCount(): number
  expandedSql(): string | null
  getStatus(status: RusqliteStatementStatus): number
  resetStatus(status: RusqliteStatementStatus): number
  isExplain(): number
  readonly(): boolean
  clearBindings(): void
}

export interface RusqliteConnectionOptions {
  flags: number
  vfs?: string
}

export interface RusqliteDetailedColumnMetadata {
  databaseName: string
  tableName: string
  columnName: string
  type?: string
  collationSequence?: string
  notNull: boolean
  primaryKey: boolean
  autoIncrement: boolean
}

export declare const enum RusqliteStatementStatus {
  FullscanStep = 1,
  Sort = 2,
  AutoIndex = 3,
  VmStep = 4,
  RePrepare = 5,
  Run = 6,
  FilterMiss = 7,
  FilterHit = 8,
  MemUsed = 99
}
