/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RusqliteColumn {
  name(): string
  declType(): string | null
}

export declare class RusqliteColumnMetadata {
  name(): string
  databaseName(): string | null
  tableName(): string | null
  originName(): string | null
}

export declare class RusqliteConnection {
  static open(path: string, options?: RusqliteConnectionOptions | undefined | null): RusqliteConnection
  static openInMemory(options?: RusqliteConnectionOptions | undefined | null): RusqliteConnection
  backup(name: string, dstPath: string, callback: ((err: Error | null, arg: Progress) => any)): void
  restore(name: string, srcPath: string, callback: ((err: Error | null, arg: Progress) => any)): void
  prepare(sql: string): RusqliteStatement
  columnExists(dbName: string | undefined | null, tableName: string, columnName: string): boolean
  tableExists(dbName: string | undefined | null, tableName: string): boolean
  columnMetadata(dbName: string | undefined | null, tableName: string, columnName: string): RusqliteConnectionColumnMetadata
  dbConfig(config: RusqliteDbConfig): void
  setDbConfig(config: RusqliteDbConfig, on: boolean): void
  pragmaQueryValue(schemaName: string | undefined | null, pragmaName: string): string
  pragmaQuery(schemaName: string | undefined | null, pragmaName: string): Array<string>
  pragma(schemaName: string | undefined | null, pragmaName: string, pragmaValue: unknown, callback: ((err: Error | null, arg: Buffer) => any)): void
  pragmaUpdate(schemaName: string | undefined | null, pragmaName: string, pragmaValue: unknown): void
  pragmaUpdateAndCheck(schemaName: string | undefined | null, pragmaName: string, pragmaValue: unknown): string
  transaction(): RusqliteTransaction
  transactionWithBehavior(behavior: RusqliteTransactionBehavior): RusqliteTransaction
  uncheckedTransaction(): RusqliteTransaction
  savepoint(): RusqliteSavepoint
  savepointWithName(name: string): RusqliteSavepoint
  transactionState(dbName?: string | undefined | null): RusqliteTransactionState
  setTransactionBehavior(behavior: RusqliteTransactionBehavior): void
  executeBatch(sql: string): void
  execute(sql: string, sqlParams: Array<unknown>): number

}

export declare class RusqliteRow {

}

/**
 * This type extends JavaScript's `Iterator`, and so has the iterator helper
 * methods. It may extend the upcoming TypeScript `Iterator` class in the future.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iterator_helper_methods
 * @see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-6.html#iterator-helper-methods
 */
export declare class RusqliteRows extends Iterator<string, void, void> {

  next(value?: void): IteratorResult<string, void>
}

export declare class RusqliteSavepoint {

}

export declare class RusqliteStatement {
  columnNames(): Array<string>
  columnCount(): number
  columnName(col: number): string
  columnIndex(name: string): number
  columns(): Array<RusqliteColumn>
  columnsWithMetadata(): Array<RusqliteColumnMetadata>
  columnMetadata(col: number): RusqliteDetailedColumnMetadata | null
  execute(params?: unknown[] | undefined | null): number
  insert(params?: unknown[] | undefined | null): number
  query(params?: unknown[] | undefined | null): RusqliteRows
  exists(params?: unknown[] | undefined | null): boolean
  parameterIndex(name: string): number | null
  parameterName(index: number): string | null
  parameterCount(): number
  expandedSql(): string | null
  getStatus(status: RusqliteStatementStatus): number
  resetStatus(status: RusqliteStatementStatus): number
  isExplain(): number
  readonly(): boolean
  clearBindings(): void
}

export declare class RusqliteTransaction {
  savepoint(): RusqliteSavepoint
  savepointWithName(name: string): RusqliteSavepoint
  dropBehavior(): DropBehavior
  setDropBehavior(dropBehavior: DropBehavior): void
  commit(): void
  rollback(): void
  finish(): void
}

export declare const enum DropBehavior {
  Rollback = 0,
  Commit = 1,
  Ignore = 2,
  Panic = 3
}

export interface Progress {
  remaining: number
  pageCount: number
}

export interface RusqliteConnectionColumnMetadata {
  type?: string
  collationSequence?: string
  notNull: boolean
  primaryKey: boolean
  autoIncrement: boolean
}

export interface RusqliteConnectionOptions {
  flags: number
  vfs?: string
}

export declare const enum RusqliteDbConfig {
  SqliteDbconfigEnableFkey = 1002,
  SqliteDbconfigEnableTrigger = 1003,
  SqliteDbconfigEnableFts3Tokenizer = 1004,
  SqliteDbconfigNoCkptOnClose = 1006,
  SqliteDbconfigEnableQpsg = 1007,
  SqliteDbconfigTriggerEqp = 1008,
  SqliteDbconfigResetDatabase = 1009,
  SqliteDbconfigDefensive = 1010,
  SqliteDbconfigWritableSchema = 1011,
  SqliteDbconfigLegacyAlterTable = 1012,
  SqliteDbconfigDqsDml = 1013,
  SqliteDbconfigDqsDdl = 1014,
  SqliteDbconfigEnableView = 1015,
  SqliteDbconfigLegacyFileFormat = 1016,
  SqliteDbconfigTrustedSchema = 1017,
  SqliteDbconfigStmtScanStatus = 1018,
  SqliteDbconfigReverseScanOrder = 1019,
  SqliteDbconfigEnableAttachCreate = 1020,
  SqliteDbconfigEnableAttachWrite = 1021,
  SqliteDbconfigEnableComments = 1022
}

export interface RusqliteDetailedColumnMetadata {
  databaseName: string
  tableName: string
  columnName: string
  type?: string
  collationSequence?: string
  notNull: boolean
  primaryKey: boolean
  autoIncrement: boolean
}

export declare const enum RusqliteStatementStatus {
  FullscanStep = 1,
  Sort = 2,
  AutoIndex = 3,
  VmStep = 4,
  RePrepare = 5,
  Run = 6,
  FilterMiss = 7,
  FilterHit = 8,
  MemUsed = 99
}

export declare const enum RusqliteTransactionBehavior {
  Deferred = 0,
  Immediate = 1,
  Exclusive = 2
}

export declare const enum RusqliteTransactionState {
  None = 0,
  Read = 1,
  Write = 2
}
