/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Column {
  name(): string
  declType(): string | null
}

export declare class ColumnMetadata {
  name(): string
  databaseName(): string | null
  tableName(): string | null
  originName(): string | null
}

export declare class Connection {
  static open(path: string, options?: ConnectionOptions | undefined | null): Connection
  static openInMemory(options?: ConnectionOptions | undefined | null): Connection
  columnExists(dbName: string | undefined | null, tableName: string, columnName: string): boolean
  tableExists(dbName: string | undefined | null, tableName: string): boolean
  columnMetadata(dbName: string | undefined | null, tableName: string, columnName: string): ConnectionColumnMetadata
  dbConfig(config: RusqliteDbConfig): void
  setDbConfig(config: RusqliteDbConfig, on: boolean): void
  pragmaQueryValue(schemaName: string | undefined | null, pragmaName: string): unknown
  pragmaQuery(schemaName: string | undefined | null, pragmaName: string): Record<string,unknown>
  pragma(schemaName: string | undefined | null, pragmaName: string, pragmaValue: unknown[], callback: (value:Record<string,unknown>) => void): void
  pragmaUpdate(schemaName: string | undefined | null, pragmaName: string, pragmaValue: unknown[]): Promise<void>
  pragmaUpdateAndCheck(schemaName: string | undefined | null, pragmaName: string, pragmaValue: unknown[]): Record<string,unknown>
  transaction(callback: (connection: ScopedConnection) => void): void
  transactionWithBehavior(behavior: TransactionBehavior, callback: (connection: ScopedConnection) => void): void
  uncheckedTransaction(callback: (connection: ScopedConnection) => void): void
  savepoint(callback: (transaction: ScopedConnection) => void): void
  savepointWithName(name: String, callback: (transaction: ScopedConnection) => void): void
  transactionState(dbName?: string | undefined | null): TransactionState
  setTransactionBehavior(behavior: TransactionBehavior): void
  executeBatch(sql: string): void
  execute(sql: string, sqlParams: unknown[]): number
  path(): string
  releaseMemory(): void
  lastInsertRowid(): number
  queryRow(sql: string, sqlParams: unknown[]): Record<string,unknown>
  queryOne(sql: string, params: unknown[]): Record<string,unknown>
  prepare(sql: String, callback: (statement: ScopedStatement) => void): void
  prepareWithFlags(sql: string, flags: RusqlitePrepFlags, callback: any): void
  getInterruptHandle(): InterruptHandle
  changes(): number
  totalChanges(): number
  isAutocommit(): boolean
  isBusy(): boolean
  cacheFlush(): void
  isReadonly(dbName: string): boolean
  dbName(index: number): string
  isInterrupted(): boolean

}

export declare class InterruptHandle {
  interrupt(): void
}

/**
 * This type extends JavaScript's `Iterator`, and so has the iterator helper
 * methods. It may extend the upcoming TypeScript `Iterator` class in the future.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iterator_helper_methods
 * @see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-6.html#iterator-helper-methods
 */
export declare class RowIterator extends Iterator<unknown, number, number> {

  next(value?: number): IteratorResult<unknown, number>
}

export declare class Rows {
  toJSON(): unknown
  iterate(): RowIterator
  get(index: number): unknown | null
}

export declare class ScopedConnection {
  columnExists(dbName: string | undefined | null, tableName: string, columnName: string): boolean
  tableExists(dbName: string | undefined | null, tableName: string): boolean
  columnMetadata(dbName: string | undefined | null, tableName: string, columnName: string): ConnectionColumnMetadata
  dbConfig(config: RusqliteDbConfig): void
  setDbConfig(config: RusqliteDbConfig, on: boolean): void
  pragmaQueryValue(schemaName: string | undefined | null, pragmaName: string): unknown
  pragmaQuery(schemaName: string | undefined | null, pragmaName: string): Record<string,unknown>
  pragma(schemaName: string | undefined | null, pragmaName: string, pragmaValue: unknown[], callback: (value: Record<string, unknown>) => void): void
  pragmaUpdate(schemaName: string | undefined | null, pragmaName: string, pragmaValue: unknown[]): void
  pragmaUpdateAndCheck(schemaName: string | undefined | null, pragmaName: string, pragmaValue: unknown[]): Record<string,unknown>
  savepoint(callback: (transaction: ScopedConnection) => void): void
  savepointWithName(name: string, callback: (transaction: ScopedConnection) => void): void
  transactionState(dbName?: string | undefined | null): TransactionState
  executeBatch(sql: string): void
  execute(sql: string, sqlParams: unknown[]): number
  path(): string
  releaseMemory(): void
  lastInsertRowid(): number
  queryRow(sql: string, sqlParams: unknown[]): Record<string,unknown>
  queryOne(sql: string, sqlParams: unknown[]): Record<string,unknown>
  prepare(sql:string, callback: (statement: ScopedStatement) => void): void
  prepareWithFlags(sql:string, flags: RusqlitePrepFlags, callback: (statement: ScopedStatement) => void): void
  getInterruptHandle(): InterruptHandle
  changes(): number
  totalChanges(): number
  isAutocommit(): boolean
  isBusy(): boolean
  cacheFlush(): void
  isReadonly(dbName: string): boolean
  dbName(index: number): string
  isInterrupted(): boolean
}

export declare class ScopedStatement {
  columnNames(): Array<string>
  columnCount(): number
  columnName(col: number): string
  columnIndex(name: string): number
  columns(): Array<Column>
  columnsWithMetadata(): Array<ColumnMetadata>
  columnMetadata(col: number): RusqliteDetailedColumnMetadata | null
  execute(params: unknown[]): number
  insert(params: unknown[]): number
  query(params: unknown[]): Rows
  exists(params: unknown[]): boolean
  parameterIndex(name: string): number | null
  parameterName(index: number): string | null
  parameterCount(): number
  expandedSql(): string | null
  getStatus(status: RusqliteStatementStatus): number
  resetStatus(status: RusqliteStatementStatus): number
  isExplain(): number
  readonly(): boolean
  clearBindings(): void

}

export interface ConnectionColumnMetadata {
  type?: string
  collationSequence?: string
  notNull: boolean
  primaryKey: boolean
  autoIncrement: boolean
}

export interface ConnectionOptions {
  flags?: number
  vfs?: string
}

export declare const enum DropBehavior {
  Rollback = 0,
  Commit = 1,
  Ignore = 2,
  Panic = 3
}

export declare const enum OpenFlags {
  SqliteOpenReadonly = 1,
  SqliteOpenReadwrite = 2,
  SqliteOpenCreate = 4,
  SqliteOpenDELETEONCLOSE = 8,
  SqliteOpenEXCLUSIVE = 16,
  SqliteOpenAUTOPROXY = 32,
  SqliteOpenURI = 64,
  SqliteOpenMEMORY = 128,
  SqliteOpenMainDb = 256,
  SqliteOpenTempDb = 512,
  SqliteOpenTransientDb = 1024,
  SqliteOpenMainJournal = 2048,
  SqliteOpenTempJournal = 4096,
  SqliteOpenSubjournal = 8192,
  SqliteOpenSuperJournal = 16384,
  SqliteOpenNomutex = 32768,
  SqliteOpenFullmutex = 65536,
  SqliteOpenSharedcache = 131072,
  SqliteOpenPrivatecache = 262144,
  SqliteOpenWal = 524288,
  SqliteOpenNofollow = 16777216,
  SqliteOpenExrescode = 33554432
}

export interface Progress {
  remaining: number
  pageCount: number
}

export declare const enum RusqliteDbConfig {
  SqliteDbconfigEnableFkey = 1002,
  SqliteDbconfigEnableTrigger = 1003,
  SqliteDbconfigEnableFts3Tokenizer = 1004,
  SqliteDbconfigNoCkptOnClose = 1006,
  SqliteDbconfigEnableQpsg = 1007,
  SqliteDbconfigTriggerEqp = 1008,
  SqliteDbconfigResetDatabase = 1009,
  SqliteDbconfigDefensive = 1010,
  SqliteDbconfigWritableSchema = 1011,
  SqliteDbconfigLegacyAlterTable = 1012,
  SqliteDbconfigDqsDml = 1013,
  SqliteDbconfigDqsDdl = 1014,
  SqliteDbconfigEnableView = 1015,
  SqliteDbconfigLegacyFileFormat = 1016,
  SqliteDbconfigTrustedSchema = 1017,
  SqliteDbconfigStmtScanStatus = 1018,
  SqliteDbconfigReverseScanOrder = 1019,
  SqliteDbconfigEnableAttachCreate = 1020,
  SqliteDbconfigEnableAttachWrite = 1021,
  SqliteDbconfigEnableComments = 1022
}

export interface RusqliteDetailedColumnMetadata {
  databaseName: string
  tableName: string
  columnName: string
  type?: string
  collationSequence?: string
  notNull: boolean
  primaryKey: boolean
  autoIncrement: boolean
}

export declare const enum RusqlitePrepFlags {
  SqlitePreparePersistent = 1,
  SqlitePrepareNoVtab = 4,
  SqlitePrepareDontLog = 16
}

export declare const enum RusqliteStatementStatus {
  FullscanStep = 1,
  Sort = 2,
  AutoIndex = 3,
  VmStep = 4,
  RePrepare = 5,
  Run = 6,
  FilterMiss = 7,
  FilterHit = 8,
  MemUsed = 99
}

export declare const enum TransactionBehavior {
  Deferred = 0,
  Immediate = 1,
  Exclusive = 2
}

export declare const enum TransactionState {
  None = 0,
  Read = 1,
  Write = 2
}
