/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export declare class Column {
  name(): string
  declType(): string | null
}

export declare class ColumnMetadata {
  name(): string
  databaseName(): string | null
  tableName(): string | null
  originName(): string | null
}

/**
 * This type extends JavaScript's `Iterator`, and so has the iterator helper
 * methods. It may extend the upcoming TypeScript `Iterator` class in the future.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iterator_helper_methods
 * @see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-6.html#iterator-helper-methods
 */
export declare class Rows extends Iterator<unknown, void, void> {
  toJSON(): string
  next(value?: void): IteratorResult<unknown, void>
}

export declare class RusqliteConnection {
  static open(path: string, options?: RusqliteConnectionOptions | undefined | null): RusqliteConnection
  static openInMemory(options?: RusqliteConnectionOptions | undefined | null): RusqliteConnection
  backup(name: string, dstPath: string, callback: ((err: Error | null, arg: Progress) => any)): void
  restore(name: string, srcPath: string, callback: ((err: Error | null, arg: Progress) => any)): void
  columnExists(dbName: string | undefined | null, tableName: string, columnName: string): boolean
  tableExists(dbName: string | undefined | null, tableName: string): boolean
  columnMetadata(dbName: string | undefined | null, tableName: string, columnName: string): ConnectionColumnMetadata
  dbConfig(config: RusqliteDbConfig): void
  setDbConfig(config: RusqliteDbConfig, on: boolean): void
  pragmaQueryValue(schemaName: string | undefined | null, pragmaName: string): Buffer
  pragmaQuery(schemaName: string | undefined | null, pragmaName: string): Buffer
  pragma(schemaName: string | undefined | null, pragmaName: string, pragmaValue: Uint8Array, callback: ((err: Error | null, arg: Buffer) => any)): void
  pragmaUpdate(schemaName: string | undefined | null, pragmaName: string, pragmaValue: Uint8Array): void
  pragmaUpdateAndCheck(schemaName: string | undefined | null, pragmaName: string, pragmaValue: Uint8Array): Buffer
  transaction(callback: (transaction: ScopedTransaction) => void): void
  transactionWithBehavior(behavior: TransactionBehavior, callback: (transaction: ScopedTransaction) => void): void
  uncheckedTransaction(callback: (transaction: ScopedTransaction) => void): void
  savepoint(): ScopedSavepoint
  savepointWithName(name: string): ScopedSavepoint
  transactionState(dbName?: string | undefined | null): TransactionState
  setTransactionBehavior(behavior: TransactionBehavior): void
  executeBatch(sql: string): void
  execute(sql: string, sqlParams: Uint8Array): number
  path(): string
  releaseMemory(): void
  lastInsertRowid(): number
  queryRow(sql: string, sqlParams: Uint8Array): Buffer
  queryOne(sql: string, sqlParams: Uint8Array): Buffer
  prepare(sql: string): ScopedStatement
  prepareWithFlags(sql: string, flags: RusqlitePrepFlags): ScopedStatement
  getInterruptHandle(): RusqliteInterruptHandle
  changes(): number
  totalChanges(): number
  isAutocommit(): boolean
  isBusy(): boolean
  cacheFlush(): void
  isReadonly(dbName: string): boolean
  dbName(index: number): string
  isInterrupted(): boolean

}

export declare class RusqliteInterruptHandle {
  interrupt(): void
}

export declare class RusqliteSharedConnection {
  backup(name: string, dstPath: string, callback: ((err: Error | null, arg: Progress) => any)): void
  restore(name: string, srcPath: string, callback: ((err: Error | null, arg: Progress) => any)): void
  columnExists(dbName: string | undefined | null, tableName: string, columnName: string): boolean
  tableExists(dbName: string | undefined | null, tableName: string): boolean
  columnMetadata(dbName: string | undefined | null, tableName: string, columnName: string): ConnectionColumnMetadata
  dbConfig(config: RusqliteDbConfig): void
  setDbConfig(config: RusqliteDbConfig, on: boolean): void
  pragmaQueryValue(schemaName: string | undefined | null, pragmaName: string): Buffer
  pragmaQuery(schemaName: string | undefined | null, pragmaName: string): Buffer
  pragma(schemaName: string | undefined | null, pragmaName: string, pragmaValue: Uint8Array, callback: ((err: Error | null, arg: Buffer) => any)): void
  pragmaUpdate(schemaName: string | undefined | null, pragmaName: string, pragmaValue: Uint8Array): void
  pragmaUpdateAndCheck(schemaName: string | undefined | null, pragmaName: string, pragmaValue: Uint8Array): Buffer
  uncheckedTransaction(reference: RusqliteConnection): ScopedTransaction
  transactionState(dbName?: string | undefined | null): TransactionState
  executeBatch(sql: string): void
  execute(sql: string, sqlParams: Uint8Array): number
  path(): string
  releaseMemory(): void
  lastInsertRowid(): number
  queryRow(sql: string, sqlParams: Uint8Array): Buffer
  queryOne(sql: string, sqlParams: Uint8Array): Buffer
  prepare(sql: string): ScopedStatement
  prepareWithFlags(sql: string, flags: RusqlitePrepFlags): ScopedStatement
  getInterruptHandle(): RusqliteInterruptHandle
  changes(): number
  totalChanges(): number
  isAutocommit(): boolean
  isBusy(): boolean
  cacheFlush(): void
  isReadonly(dbName: string): boolean
  dbName(index: number): string
  isInterrupted(): boolean
}

export declare class ScopedSavepoint {
  savepoint(reference: RusqliteConnection): ScopedSavepoint
  savepointWithName(reference: RusqliteConnection, name: string): ScopedSavepoint
  dropBehavior(): DropBehavior
  setDropBehavior(dropBehavior: DropBehavior): void
  commit(): void
  rollback(): void
  finish(): void
  get connection(): RusqliteSharedConnection
}

export declare class ScopedStatement {
  columnNames(): Array<string>
  columnCount(): number
  columnName(col: number): string
  columnIndex(name: string): number
  columns(): Array<Column>
  columnsWithMetadata(): Array<ColumnMetadata>
  columnMetadata(col: number): RusqliteDetailedColumnMetadata | null
  execute(params: Uint8Array): number
  insert(params: Uint8Array): number
  query(params: Uint8Array): Rows
  exists(params: Uint8Array): boolean
  parameterIndex(name: string): number | null
  parameterName(index: number): string | null
  parameterCount(): number
  expandedSql(): string | null
  getStatus(status: RusqliteStatementStatus): number
  resetStatus(status: RusqliteStatementStatus): number
  isExplain(): number
  readonly(): boolean
  clearBindings(): void
}

export declare class ScopedTransaction {
  /** savepoint */
  savepoint(reference: RusqliteConnection): ScopedSavepoint
  savepointWithName(reference: RusqliteConnection, name: string): ScopedSavepoint
  get connection(): RusqliteSharedConnection
}

export interface ConnectionColumnMetadata {
  type?: string
  collationSequence?: string
  notNull: boolean
  primaryKey: boolean
  autoIncrement: boolean
}

export declare const enum DropBehavior {
  Rollback = 0,
  Commit = 1,
  Ignore = 2,
  Panic = 3
}

export declare function executeBatch(external: ExternalObject<RusqliteConnection>, sql: string): void

export interface Progress {
  remaining: number
  pageCount: number
}

export interface RusqliteConnectionOptions {
  flags: number
  vfs?: string
}

export declare const enum RusqliteDbConfig {
  SqliteDbconfigEnableFkey = 1002,
  SqliteDbconfigEnableTrigger = 1003,
  SqliteDbconfigEnableFts3Tokenizer = 1004,
  SqliteDbconfigNoCkptOnClose = 1006,
  SqliteDbconfigEnableQpsg = 1007,
  SqliteDbconfigTriggerEqp = 1008,
  SqliteDbconfigResetDatabase = 1009,
  SqliteDbconfigDefensive = 1010,
  SqliteDbconfigWritableSchema = 1011,
  SqliteDbconfigLegacyAlterTable = 1012,
  SqliteDbconfigDqsDml = 1013,
  SqliteDbconfigDqsDdl = 1014,
  SqliteDbconfigEnableView = 1015,
  SqliteDbconfigLegacyFileFormat = 1016,
  SqliteDbconfigTrustedSchema = 1017,
  SqliteDbconfigStmtScanStatus = 1018,
  SqliteDbconfigReverseScanOrder = 1019,
  SqliteDbconfigEnableAttachCreate = 1020,
  SqliteDbconfigEnableAttachWrite = 1021,
  SqliteDbconfigEnableComments = 1022
}

export interface RusqliteDetailedColumnMetadata {
  databaseName: string
  tableName: string
  columnName: string
  type?: string
  collationSequence?: string
  notNull: boolean
  primaryKey: boolean
  autoIncrement: boolean
}

export declare const enum RusqlitePrepFlags {
  SqlitePreparePersistent = 1,
  SqlitePrepareNoVtab = 4,
  SqlitePrepareDontLog = 16
}

export declare const enum RusqliteStatementStatus {
  FullscanStep = 1,
  Sort = 2,
  AutoIndex = 3,
  VmStep = 4,
  RePrepare = 5,
  Run = 6,
  FilterMiss = 7,
  FilterHit = 8,
  MemUsed = 99
}

export declare const enum TransactionBehavior {
  Deferred = 0,
  Immediate = 1,
  Exclusive = 2
}

export declare const enum TransactionState {
  None = 0,
  Read = 1,
  Write = 2
}
